### ISSUE TITLE
Node version (add .nvmrc file)

### ISSUE THREAD

**Issue by xplosionmind** [scambifestival/dfg.scambi.org#13]
Hi guys, I am building the website locally but I get a warning of my node version (currently 16.x) is not the same one you are using.

Which one should I use?  
For the sake of consistency, I believe we should add a `.nvmrc` file to universally specify the version.

**Comment by minhuyenhoang** [comment]
@xplosionmind My current node version is 16.15.1 and I was able to run without warning at all. I have added a script to check if your node version is compatible. 

In order to run that script, in your terminal or command line, before you start the project, use ```npm run prestart```. It will let you know if your node version is good.

It's PR #52 
Let me know if you still have trouble!

**Comment by xplosionmind** [comment]
Thanks, it helps a lot.

**Comment by minhuyenhoang** [comment]
Awesome! Let me know if you need any more help!
